### ISSUE TITLE
 button "forgotten password" too much heigh

### ISSUE THREAD

**Issue by PriscilliaAmmeux** [XPEHO/yaki_ui#26]
*design basti*
<img width="158" alt="Capture d’écran 2023-09-29 114712" src="https://github.com/XPEHO/yaki_ui/assets/96787811/4a97a997-96dd-4820-93ff-997ffc4f2ead">

*app*
<img width="365" alt="Capture d’écran 2023-09-29 114729" src="https://github.com/XPEHO/yaki_ui/assets/96787811/5b05c1a4-368e-482c-ae49-2520ac849470">

**Comment by LaurentMag** [comment]
updated with optional button height parameter
